tablauno:
    path:     /
    defaults: { _controller: "relacionBundle:TablaUno:index" }

tablauno_show:
    path:     /{id}/show
    defaults: { _controller: "relacionBundle:TablaUno:show" }

tablauno_new:
    path:     /new
    defaults: { _controller: "relacionBundle:TablaUno:new" }

tablauno_create:
    path:     /create
    defaults: { _controller: "relacionBundle:TablaUno:create" }
    methods:  POST

tablauno_edit:
    path:     /{id}/edit
    defaults: { _controller: "relacionBundle:TablaUno:edit" }

tablauno_update:
    path:     /{id}/update
    defaults: { _controller: "relacionBundle:TablaUno:update" }
    methods:  [POST, PUT]

tablauno_delete:
    path:     /{id}/delete
    defaults: { _controller: "relacionBundle:TablaUno:delete" }
    methods:  [POST, DELETE]
